# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc2a4e2590077f25b4ae0316fa8f978198800dbf954279c8578888d909eddd15141ac22c169a2ad1e0bf072a648f6de6dee41acb536673863413185d60ea75b1

test:
  secret_key_base: eaf7e8ffa1ed2a149117e02903f27be8ee0a2f1e491eb5000f30e79632c649596ae3e536679d932cfc0319b16a87a0019421fa34a075809a1c6fd1fdf0ee8148

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
